<?php

namespace App\Model;

use App\Observers\FangOwnerObserver;
use Illuminate\Database\Eloquent\Model;

class FangOwner extends Base
{
    //
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        FangOwner::observe(FangOwnerObserver::class);
    }

}
