<?php

namespace App\Model;

use App\Observers\FangOwnerObserver;
use Illuminate\Database\Eloquent\Model;

class FangOwner extends Base
{
    //
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        FangOwner::observe(FangOwnerObserver::class);
    }

    //获取器
    public function getPicsAttribute()
    {
        $arr = explode('#',$this->attributes['pic']);
        array_shift($arr);
        return $arr;

    }

}
