<?php

namespace App\Model;

use App\Observers\FangAttrObserver;
use Illuminate\Database\Eloquent\Model;

class FangAttr extends Base
{
    //
    protected $appends= ['actionBtn'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        FangAttr::observe(FangAttrObserver::class);
    }

    public function getActionBtnAttribute()
    {
        return $this->editBtn('admin.fangAttr.edit') . ' ' . $this->delBtn('admin.fangAttr.destroy');

    }


}
